### ISSUE TITLE
MODS validation - Errors retrieving schema?

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/iipqa#11]
Ran iipqa on a set of newspapers generated by MIK CSV Newspapers toolchain, and got the same errors over and over:

> Warning: DOMDocument::schemaValidateSource(): attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does not resolve to a(n) attribute declaration. in /Users/Brandon/iipqa/src/utils/ModsValidator.php on line 91
> 
> Warning: DOMDocument::schemaValidateSource(): Invalid Schema in /Users/Brandon/iipqa/src/utils/ModsValidator.php on line 91
> 
> Warning: DOMDocument::schemaValidateSource(): I/O warning : failed to load external entity "src/utils/xml.xsd" in /Users/Brandon/iipqa/src/utils/ModsValidator.php on line 91
> 
> Warning: DOMDocument::schemaValidateSource(): Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location 'src/utils/xml.xsd'. Skipping the import. in /Users/Brandon/iipqa/src/utils/ModsValidator.php on line 91

Wondering if the problems with the schema are related to that "failure to load" error (third one).

**Comment by mjordan** [comment]
Can you confirm that your `src/utils` contains the MODS schema .xsd file?

**Comment by bondjimbond** [comment]
Looks like it doesn't! I didn't get the 'wget not recognized' error, so assumed the XSD downloaded correctly. Will grab them and see what happens.

**Comment by bondjimbond** [comment]
OK - that worked! Thanks. Don't know why I didn't get the wget error.

Thanks to the MODS validation I found yet another problem with my 21 GB of theses from UNBC. Sigh.

**Comment by mjordan** [comment]
Great. We need a way to generate MODS without needing to move or even have access to those TIFFs. We have it for the single-file CSV toolchain; let's see if we can add it to all CSV toolchains.
